### PR TITLE
add Zilean to Shurima champ list

### PR DESCRIPTION
**Pull request by Pomarine**
- Add Zilean to Shurima champs list (he was missing before)

### CODE REVIEW

**Comment by Pomarine** [comment]
image

image

**Comment by Pomarine** [comment]
There are more mistakes in the champion lists which I have not amended yet, where did  you get these lists from?

**Comment by TheRaphael0000** [comment]
Hello, thank you for your changes.
I created the JSON myself from the client. I did it a few weeks ago. Looks like Riot changed the lists in the meantime. (For example, I had to add Bel'Veth manually, since it was not released when I created the file)
Here a few screenshots, my friend and I did May the 15th.
I don't know if these can be found directly from Riot's API, but that would be great.

unknown
unknown (1)
unknown (2)

**Comment by Pomarine** [comment]
Unfortunately the riot api does not provide these lists so it will have to be done manually 😢.
I may manually double check all the lists are up to date sometime in the near future and submit another pull request.

**Pull request merged**
