### PR TITLE
add share feature to the team builder

### PR DESCRIPTION
**Pull request by DarkIntaqt**
Additions:
- add share button with tooltip
- generate a sharable url
- decode shared url to show features

### CODE REVIEW

**Comment by TheRaphael0000** [comment]
Hi, thanks for your pull request :)

I've changed a few things and explained it in the commit (kind of).

The main thing was that I didn't like too much the fact that the user see the comma separated selection, so I wanted to avoid this.

My first idea was to have a bit field the following way: All challenges and champions have a bit 0 if not selected 1 if selected. It yields a bit long bit field with mostly 0s. Convert it to base64 and voilà.

But there is a problem with this approach: It doesn't take into account new champions :/ (in case we order them by champion_id for the bit field) since Riot doesn't just increase a counter for the champion ID, we can't be sure the bit field will be concistant across patches since we don't know where new champions are in the bit field. A solution would be to have a lookup table or a personal ID that we update ourself, but it's too much of a bother.

Soooo, I decided to just convert your selection code to base64. But since we go from ascii to base64 and not binary to base64 it increase the length of the code .-. To avoid having too long URLs I've decided to remove the challenge selection from the URL since its not that useful, I think.

If you can just give me your insight on this, I'll be glad :).
Thanks !

**Comment by DarkIntaqt** [comment]
First, your solution sounds good!
Personally, I would like to share selected challenges as well. We could agree on share only a single challenge, but I think it would be pretty useful to share a link like: "you can play X champions for Y challenge". I know that these selections are only a click away, but in the end we are all rather comfortable. 
I am sure that there is a better implementation of the problem I created, but I think I got the best possible solution without changing the other code

**Comment by TheRaphael0000** [comment]
Yeah but the challenges that the composition yield are in yellow already that's why I didn't find it useful.

image

**Comment by DarkIntaqt** [comment]
On the other hand you could share: "we are doing this challenge, which others should we do"
We could do it as the following with the linking structure to prevent larger urls than necessary:
1. Champions Base64
2. Separator if challenges are set
3. Challenges Base64
I would definitely not base64 encode the separator. 
Then, if you have only selected a challenge the url would look like this: `#[separator]56ad`, so (as I would use a minus as separator because it isn't used in base64 and still recognised as a port of an url): `#-56ad`. I made this base64 string up
And if only champions are set it could be the following: `#base64championstring`
If both are set the hash would look like this `#base64championstring-56ad`. That would basically use your solution, as long as no challenge is set and still open doors for the possibility that someone wants to share a challenge. 

In the end it is your decision. I know that the "yellow" mark is very good already, as long as you want to share your champion selection and not your challenges. 
Maybe my solution is sort of a "middle way solution" to the problem. 

**ALSO:** is the base64 encoded string with or without the double equal signs (==)? Usually all base64 strings have these but they would only fill up unnecessary space.

**Comment by DarkIntaqt** [comment]
Also, you removed this part in your commit from the share button click. I think it is mandatory to give the user a visual feedback when copying something to the users clipboard. 
https://github.com/TheRaphael0000/tahm-ken.ch/blob/28fef523637e421dd4d879d4dcf6799183cbf96e/static/js/team_builder.js#L514-L523
The code changes the button color to green for 1.5 seconds and replace the copy icon with a check mark icon.

**Comment by TheRaphael0000** [comment]
I've added an implementation with the bitfield. We can probably also compress this bitfield with Huffman Coding since there are a lots of 0s. I just need to find a good JS implementation.

**Comment by TheRaphael0000** [comment]
Hum there still is a bug. I'll fix it this afternoon

**Comment by TheRaphael0000** [comment]
Ok, it's fixed!

For this selection:

image

We have this URL:

http://127.0.0.1:8000/team_builder?#BkAAAA-Bard,Maokai,KSante,Nidalee,Ziggs

Tell me what you think and if it ok, i'll merge it. Btw I've readded the animation for the clipboard feedback.

**Comment by DarkIntaqt** [comment]
Looks good to me!

**Pull request merged**
